### PR TITLE
Feat: record query metrics

### PR DESCRIPTION
**Pull request by hopeyen**
Track query volume and performance like the original indexer service.
Some metrics from the original are registered but not used so they are not included here

Part of https://github.com/graphops/indexer-service-rs/issues/4

For later: Add cost model metrics once there is cost server

### CODE REVIEW

**Comment by aasseman** [comment]
:thinking: shouldn't the query duration be discarded if there's an error? I don't know what the choice was in the original indexer-service though.

**Comment by aasseman** [comment]
And I also have similar question about `FAILED_QUERIES`. Shouldn't it be incremented at all the points where the functions returns with an error?

**Comment by hopeyen** [comment]
The typescript version uses the syntax `try { start_timer and stuff } catch { error_handle } finally { stop_timer }` in which `finally` should happen regardless of `try` result, so it does record errored out queries. 
Does it make more sense to just discard? maybe I add another label with an Enum on the results🤔?

**Comment by aasseman** [comment]
Yup I see, thanks for the pointers, yours indeed behaves like the original. IMO the original is wrong though :grimacing: .
Should we just go ahead with this, and perhaps track a potential rework of the query processing monitoring logic in the issues?

**Review by aasseman — APPROVED** [review]

**Comment by hopeyen** [comment]
I agree with you 😂 We can change it up later, will add a note to the metrics tracking issue #4

**Pull request merged**
