### PR TITLE
fix(#57): malformed indexing status response

### LINKED ISSUE #57: malformed indexing status response
The `/status` route seems to be returning a JSON string value of the expected response body. Example:
```json
"{\"data\":{\"indexingStatuses\":[{\"subgraph\":\"QmNmVRCM39PKPXqC9HNFSGW9WQWzDTWUEmpLktAd26vYCQ\",\"chains\":[{\"network\":\"hardhat\",\"latestBlock\":{\"number\":\"599\",\"hash\":\"cd3e683d1b9c8829f21b0a0c39a00ec4ec67fdb38756fcf4a275121de177ba9b\"},\"earliestBlock\":{\"number\":\"0\",\"hash\":\"0x0\"}}]},{\"subgraph\":\"QmRR4o5jApp3v7Wcym6o8dXJtBo2chnxDyFyKt12nK6eTE\",\"chains\":[{\"network\":\"hardhat\",\"latestBlock\":{\"number\":\"2265\",\"hash\":\"ca89f224b4e310a790266b94608e270b01072e514c2a5ec70f4ddf580837bc64\"},\"earliestBlock\":{\"number\":\"0\",\"hash\":\"0x0\"}}]},{\"subgraph\":\"QmeVg9Da6uyBvjUEy5JqCgw2VKdkTxjPvcYuE5riGpkqw1\",\"chains\":[{\"network\":\"hardhat\",\"latestBlock\":{\"number\":\"2312\",\"hash\":\"64272c37ada8842f1dec2fb0e7ee2f5e43684d0c1080b791223aa100ad194174\"},\"earliestBlock\":{\"number\":\"0\",\"hash\":\"0x0\"}}]},{\"subgraph\":\"QmTcYL6jsUDW2y8QE4zre7jgS26qen7PCURSdymsaVL9cG\",\"chains\":[{\"network\":\"hardhat\",\"latestBlock\":{\"number\":\"2312\",\"hash\":\"64272c37ada8842f1dec2fb0e7ee2f5e43684d0c1080b791223aa100ad194174\"},\"earliestBlock\":{\"number\":\"0\",\"hash\":\"0x0\"}}]}]}}"
```
Example response from the TS indexer-service in the same environment (expected):
```json
{"data":{"indexingStatuses":[{"subgraph":"QmNmVRCM39PKPXqC9HNFSGW9WQWzDTWUEmpLktAd26vYCQ","chains":[{"network":"hardhat","latestBlock":{"number":"599","hash":"cd3e683d1b9c8829f21b0a0c39a00ec4ec67fdb38756fcf4a275121de177ba9b"},"earliestBlock":{"number":"0","hash":"0x0"}}]},{"subgraph":"QmRR4o5jApp3v7Wcym6o8dXJtBo2chnxDyFyKt12nK6eTE","chains":[{"network":"hardhat","latestBlock":{"number":"2265","hash":"ca89f224b4e310a790266b94608e270b01072e514c2a5ec70f4ddf580837bc64"},"earliestBlock":{"number":"0","hash":"0x0"}}]},{"subgraph":"QmeVg9Da6uyBvjUEy5JqCgw2VKdkTxjPvcYuE5riGpkqw1","chains":[{"network":"hardhat","latestBlock":{"number":"2328","hash":"ed848b1de1913d3f857026bd48f2f5574ae547657c2df3c77e815e3e0333c3ba"},"earliestBlock":{"number":"0","hash":"0x0"}}]},{"subgraph":"QmTcYL6jsUDW2y8QE4zre7jgS26qen7PCURSdymsaVL9cG","chains":[{"network":"hardhat","latestBlock":{"number":"2328","hash":"ed848b1de1913d3f857026bd48f2f5574ae547657c2df3c77e815e3e0333c3ba"},"earliestBlock":{"number":"0","hash":"0x0"}}]}]}}
```
## steps to reproduce
```bash
curl http://${host}:${port}/status \
  -H 'content-type: application/json' \
  -d '{"query": "{ indexingStatuses(subgraphs: []) { subgraph chains { network latestBlock { number hash } earliestBlock { number hash } } } }"}'
```

### PR DESCRIPTION
**Pull request by Theodus**
resolves #57

### CODE REVIEW

**Review by hopeyen — APPROVED** [review]

**Comment by hopeyen** [comment]
looks good, I think we can keep the blocked field changes (will reset the revert commit and make a better fix later on)

**Review by hopeyen — APPROVED** [review]
okay should be good now:)

**Comment by aasseman** [comment]
We probably need some tests for these so that we can make sure we get the same outputs as the TS version.

**Comment by hopeyen** [comment]
sent an invite @Theodus ! thank you for contributing:)

**Pull request merged**
